### ISSUE TITLE
Why remote pc's webcam is not streaming the video

### ISSUE THREAD

**Issue by pariharatul** [Vinnu1/simple-videochat-webrtc#1]
localhost:3000 is working perfectly fine. But when I tried to use it on the remote pc, the connection is established but no video is streaming. Why this has happened?

**Comment by Vinnu1** [comment]
I'm assuming you're trying to connect two separate devices via internet, one of them is a PC which has an attached webcam. When you open the webpage on browser in that PC, you can select the camera while giving access permissions. 
This webapp is hosted over here(for now) - https://simple-videochat.herokuapp.com/ 
You can test it out. Open this url in two separate devices.

**Comment by Vinnu1** [comment]
I believe this issue is resolved.
