### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by dejakhar** [Vinnu1/simple-videochat-webrtc#4]
Hi,
I tried to replicate this app. I am able to run is on localhost but it is not working after deployment publicly. I have hosted my app on https://simple-video-chat-webrtc.now.sh/
Can you help me debugging it?
Thanks.

**Comment by jcortesebustos** [comment]
I having same trouble

**Comment by johnnynumber4** [comment]
Hey, I am also having this issue, anyone figure this out?  I am hosting on Netlify and can't figure out why it isn't working...

**Comment by johnnynumber4** [comment]
@Vinnu1 do I need to do anything with the files to allow to be hosted?

**Comment by Vinnu1** [comment]
@dejakhar @jcortesebustos @johnnynumber4 
Hi, sorry for the late reply. I didn't get an email until I got tagged. 
@dejakhar in your site, in console it is saying "io is not defined", so it couldn't find client-side socket io. I have limited experience with zeit, but I think it can host only static and serverless apps now, and this app has a server. Same with Netlify, you can only host static or serverless apps. 

So, if you want to only use Zeit or Netlify, you'll have to convert this app to serverless, for which tutorials can be found online easily OR just upload to a cloud which supports server apps, like heruko or digital ocean.

Hope this helps.
